# Generated by Django 5.0 on 2023-12-17 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=64)),
                ('name_ar', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'كلية',
                'verbose_name_plural': 'الكليات',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=64)),
                ('name_ar', models.CharField(max_length=64)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='resources.college')),
            ],
            options={
                'verbose_name': 'الدائرة',
                'verbose_name_plural': 'الدوائر',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('major_code', models.CharField(max_length=4, primary_key=True, serialize=False, unique=True)),
                ('name_en', models.CharField(max_length=64)),
                ('name_ar', models.CharField(max_length=64)),
                ('is_pseudo_major', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='majors', to='resources.department')),
            ],
            options={
                'verbose_name': 'التخصص',
                'verbose_name_plural': 'التخصصات',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=10, unique=True)),
                ('name_en', models.CharField(max_length=64)),
                ('name_ar', models.CharField(max_length=64)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='resources.department')),
                ('majors', models.ManyToManyField(blank=True, related_name='courses', to='resources.major')),
            ],
            options={
                'verbose_name': 'المساق',
                'verbose_name_plural': 'المساقات',
            },
        ),
        migrations.CreateModel(
            name='ResourceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_groups', to='resources.course')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('resource_type', models.CharField(blank=True, choices=[('formats', 'Formats'), ('slides', 'Slides'), ('books', 'Books'), ('book-solutions', 'Book Solutions'), ('lecture-notes', 'Lecture Notes'), ('projects', 'Projects'), ('other', 'Other'), ('homeworks', 'Homeworks')], max_length=20, null=True)),
                ('is_link', models.BooleanField(default=False)),
                ('resource_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='resources.resourcegroup')),
            ],
            options={
                'verbose_name': 'مصدر',
                'verbose_name_plural': 'مصادر',
            },
        ),
    ]
